### ISSUE TITLE
cancel grpc `service.AddxxxHandler` return error

### ISSUE THREAD

**Issue by li1234yun** [dapr/go-sdk#100]
**Describe the solution you'd like**
Almost go router design do not return error, suggest to `AddxxxHandler` cancels `error` return, avoid many error deal, may `panic` when handler is invalid.

**Additional context**

***Refer Design***
[net/http HandleFunc](https://golang.org/pkg/net/http/#HandleFunc)
[Gin Router](https://github.com/gin-gonic/gin#using-get-post-put-patch-delete-and-options)
[fasthttp recommand third-party routers](https://github.com/valyala/fasthttp)

I do not know too much about dapr design. If I'm wrong, please just ignore it.

**Comment by mchmarny** [comment]
@li1234yun can you elaborate on this? Point maybe to code where this applies?

**Comment by li1234yun** [comment]
Code position:
[event](https://github.com/dapr/go-sdk/blob/0a93facbbaef8c0e1d2e0d3dc6ba7e0081e6bbbb/service/grpc/binding.go#L14)
[topic](https://github.com/dapr/go-sdk/blob/0a93facbbaef8c0e1d2e0d3dc6ba7e0081e6bbbb/service/grpc/topic.go#L14)

**Comment by mchmarny** [comment]
Good catch, thanks.

**Comment by mchmarny** [comment]
checks for nil handler added

**Comment by li1234yun** [comment]
Sorry for my previous expressions, what I want to express is `service.AddxxxHandler` no return result(now return is `error`). if any invalid handler may be `panic` like `gin.Router` before service start.
