### ISSUE TITLE
Expose http/grpc server address or allow listeners to be passed in

### ISSUE THREAD

**Issue by daniel-garcia** [dapr/go-sdk#111]
**Is your feature request related to a problem? Please describe.**
I am trying to use this sdk for some integration tests for dapr. The server, however, doesn't allow for the IP address of the server to be discoverable. In many build environments using hardcoded ports can lead to conflicts and discovering unused ports can lead to race conditions.

**Describe the solution you'd like**
I want the http.Server or grpc.Server to expose the address that is used by the implicit listener (if the address passed in was ":0", for example. 

or

I want to be able to pass in a net.Listener to the http or grpc server so I can control the address allocation apriori.

**Describe alternatives you've considered**
I've tried discovering an unused port, closing the listener, and passing the address of that listener. The code is cumbersome and doesn't follow conventions used by the standard library or other projects.

**Comment by daniel-garcia** [comment]
GRPC contructor: https://pkg.go.dev/github.com/dapr/go-sdk@v0.11.1/service/grpc#NewServiceWithListener
HTTP contructor: https://pkg.go.dev/github.com/dapr/go-sdk@v0.11.1/service/http#NewService

**Comment by mchmarny** [comment]
Both gRPC and HTTP service creating methods provide option to pass in the existing listeners:

* [gRPC - NewServiceWithListener(lis net.Listener)](https://github.com/dapr/go-sdk/blob/7e8d5e580cc7505abbe2007ceef1c70406c04062/service/grpc/service.go#L29)
*[HTTP - NewServiceWithMux(address string, mux *http.ServeMux)](https://github.com/dapr/go-sdk/blob/7e8d5e580cc7505abbe2007ceef1c70406c04062/service/http/service.go#L15)

Have you consider using these constructors in your tests? This allows you to set the IP and port in both cases.

**Comment by mchmarny** [comment]
I'm closing this issue as upon further review it appears that both gRPC and HTTP protocol serving clients already expose constructor with the address which requires the developer to pass in specific address. That means the developer know the port and port (e.g. `:8080`) known priory. Do describe the use-case when the existing capability is insufficient and will re-open
