### ISSUE TITLE
Have consistent method/parameter names across SDKs

### ISSUE THREAD

**Issue by msfussell** [dapr/go-sdk#117]
This is the actions from review of this issue "Consistency of API names surfaced by each SDK" dapr/dapr#2535

**Service Invocation API**
- Rename invokeService to invokeMethod
- Rename param serviceID to appId
- Rename param method to methodName

Like this
func (c *GRPCClient) invokeMethod(ctx context.Context, appID, methodName string) (out []byte, err error) 
func (c *GRPCClient) InvokeMethodWithContent(ctx context.Context, appID, methodName string, content *DataContent) (out []byte, err error) 

**State Store API**
- Rename param from store to storeName
- Rename param from data to value

For example like this on one of the APIs
func (c *GRPCClient) SaveState(ctx context.Context, storeName, key string, value []byte) error 

**Secret Store API**
- Rename param from store to storeName

For example like this
func (c *GRPCClient) GetSecret(ctx context.Context, storeName, key string, meta map[string]string) (out map[string]string, err error) 

**Binding**
- Change struct BindingInvocation  to InvokeBindingRequest
- Make sure that in BindingInvocation  struct uses name, operation, data as names.

**Pubsub**
- Rename param from component to pubsubName
- Rename param from topic to topicName
- Rename param from in to data

For example like this
func (c *GRPCClient) PublishEvent(ctx context.Context, pubsubName, topicName string, data []byte) error

**Comment by mchmarny** [comment]
Resolved in #121
