### ISSUE TITLE
InvokeMethodWithContent support http header

### ISSUE THREAD

**Issue by rrylee** [dapr/go-sdk#125]
I think support http header is very important in real world like my project

**Comment by mchmarny** [comment]
Just to clarify, you would like to see support for http headers in the three app method invocations. Did I understand it correctly?

**Comment by rrylee** [comment]
almost, maybe add a new function to support

**Comment by rrylee** [comment]
can i submit a pr for this?

**Comment by mchmarny** [comment]
> can i submit a pr for this?

Absolutely, PRs always welcomed.

**Comment by mchmarny** [comment]
Just FYI, Dapr API does not allow for HTTP Headers as it needs to account for both gRPC and HTTP protocols but as long as the called service is able to parse query string that should work as the `HTTPExtension` type has `Querystring` which is `map[string]string`.

**Comment by rrylee** [comment]
@mchmarny 
But current problem is can not set Querystring when call Invoke

**Comment by rrylee** [comment]
@mchmarny 
here，https://github.com/dapr/go-sdk/pull/127
the pr for querystring

**Comment by mchmarny** [comment]
Addressed in #127
