### ISSUE TITLE
etag mismatch returns different error code by dapr runtime

### ISSUE THREAD

**Issue by vinayada1** [dapr/go-sdk#130]
**Describe the bug**
Check if sdk needs a change to distinguish between etag mismatch and other state api issues

**To Reproduce**
Error code internal is returned when state api fails due to etag mismatch error

**Expected behavior**
dapr runtime changes the error code returned by the state apis for etag mismatch related errors and other errors. Check if the sdk needs a change. dapr/dapr#2647

**Comment by yaron2** [comment]
Now tracked in #2647. Closing this as dupe
