### ISSUE TITLE
Remove unstable dependencies.

### ISSUE THREAD

**Issue by artursouza** [dapr/go-sdk#136]
Having a dependency in the SDK might create conflicts with apps that depend on a different version of the same package. This is a problem where a dependency is still unstable (v0.x) and can have breaking changes in minor or patch upgrades.

The action item is to review the dependencies in the SDK, specially unstable versions and confirm those are required. Ideally, removing unstable dependencies.

**Comment by yaron2** [comment]
Go modules can contain multiple versions of dependencies when used by different packages.
