### ISSUE TITLE
Upgrade protoc version to v3.14.0 to keep one with dapr/dapr

### ISSUE THREAD

**Issue by skyao** [dapr/go-sdk#140]
**Is your feature request related to a problem? Please describe.**

In repo dapr/dapr, the version of protoc is v3.1.4.0.

In repo dapr/go-sdk, the version of protoc is v3.11.2.

I have to switch protoc version for these two projects (and also for java sdk)

**Describe the solution you'd like**

In all the repo, we should use the same version of protoc. Since v3.14.0 is uesd in dapr/dapr, we need to upgrade other repo to this version.

**Comment by yaron2** [comment]
Thanks, closed with #141
