### ISSUE TITLE
When will go-sdk release actor example?

### ISSUE THREAD

**Issue by leenux** [dapr/go-sdk#16]
## In what area(s)?

/area test-and-release

## Ask your question here
When will go-sdk release `actor` example?
I already study dotnet-sdk and java-sdk,But I still don't know what to write `actor` in go-sdk?

**Comment by amanbha** [comment]
@leenux Currently dapr team is focusing on creating actor framework for dotnet, java. Python is in the works. We will do go actors in future but no firm ETA at the moment. We would be happy tow ork with you if you want to contribute and create a go sdk for actors.

cc @msfussell

**Comment by leenux** [comment]
Thank you @amanbha
