### ISSUE TITLE
PublishEventfromCustomContent doesn't set DataContentType

### ISSUE THREAD

**Issue by sidecus** [dapr/go-sdk#161]
**Describe the bug**
```PublishEventfromCustomContent``` serializes the input payload to JSON and stuffs it into gRPC request. However it doesn't set the ```DataContentType``` field. Dapr later will default it to "text/plain" during event consumption - this can cause confusions.

Is this intended?

**To Reproduce**
Call PublishEventfromCustomContent to publish an event and examine the data content type.

**Expected behavior**
If the payload is JSON serialized the DataContentType should be set accordingly - "application/json" in this case.

**Comment by blackstorm** [comment]
`DataContentType` field is optional.

And PublishEvent not set `DataContentType`  too. But bytes can be anything. Is should set default content-type to `text/plain`? 

Weird~

**Comment by sidecus** [comment]
According to [dapr pub/sub specification](https://v1-rc3.docs.dapr.io/reference/api/pubsub_api/#headers), DataContentType defaults to text/plain if unspecified.

@blackstorm yeah I agree the SDK should give options to specify DataContentType explicitly.
It's very clear for HTTP apis. However for gRPC I didn't see things in the spec about how DataContentType should be handled. Suspect the option is not in the go-sdk due to this - not 100% sure though.
