### ISSUE TITLE
"invoke API is not ready" when run invoke client with "--app-port"

### ISSUE THREAD

**Issue by tpiperatgod** [dapr/go-sdk#169]
**Describe the bug**
When I followed the example in the [example](https://github.com/dapr/go-sdk/tree/main/example) to practice the invoke part, I found that I could not add the "--app-port" parameter to the command that launchs the client.

**To Reproduce**
1. launch the serving
    ```
    dapr run --app-id serving \
             --app-protocol grpc \
             --app-port 50001 \
             --dapr-grpc-port 3500 \
             --log-level debug \
             --components-path ./config \
             go run ./serving/grpc/main.go
    ```
2. launch the client with `--app-port 50002`
    ```
    dapr run --app-id caller \
             --app-port 50002 \
             --components-path ./config \
             --log-level debug \
             go run ./client/main.go
    ```
3. see the error
    ```
    == APP == panic: error invoking service: rpc error: code = Internal desc = invoke API is not ready
    ```

**Expected behavior**
Here's what it looks like in the `dapr list` if don't add `--app-port`:
```shell
~# dapr list

  APP ID  HTTP PORT  GRPC PORT  APP PORT  COMMAND               AGE  CREATED              PID
  server  38515      3500       50001     go run ./serving/...  6s   2021-06-07 23:07.47  11877
  caller  36071      33433      0         go run ./client/m...  5s   2021-06-07 23:07.48  11990
```
I'm not sure if this is a bug, but I'd like to know if it's necessary to add `--app-port`？

Thx.

**Comment by LaurenceLiZhixin** [comment]
You needn't add --app-port param when launching client side.

**Comment by tpiperatgod** [comment]
Yes, I found that too, thanks for the answer, I will close this issue
