### ISSUE TITLE
Expose GRPCClient.protoClient

### ISSUE THREAD

**Issue by ItalyPaleAle** [dapr/go-sdk#188]
**Is your feature request related to a problem? Please describe.**

In the `GRPCClient` struct, `protoClient` is the property that contains the lower-level gRPC client: https://github.com/dapr/go-sdk/blob/main/client/client.go#L165

This is currently a private property, not exposed publicly. There are situations where applications may benefit from being able to interact with this object directly, having access to the lower-level gRPC APIs.

**Describe the solution you'd like**

Create a public getter method that returns the `protoClient` object so external objects can use it.

**Describe alternatives you've considered**

There are 2 alternatives for making low-level calls, but they're both sub-par:

1. Using the Dapr HTTP APIs which don't require access to the gRPC object, but these are potentially slower and require fiddling with the correct request/response structs manually
2. Creating a new gRPC connection, but it's less efficient than reusing the existing one.

**Comment by artursouza** [comment]
You can already reuse an existing connection to dapr and have your own protoClient insteance using the same connection with this API.

My question would be which calls you are trying to make to the "raw" sidecar API that the SDK cannot provide?

**Comment by ItalyPaleAle** [comment]
@artursouza There are APIs that are available in the protobuf but aren't exposed as higher-level APIs in Dapr. For example, see #164, which I fixed with a proposed PR #174 
I am sure there are other situations when having access to a lower-level API may be desirable. The API is stable anyways (for Dapr v1), so there wouldn't be the risk of exposing unstable APIs.

**Comment by artursouza** [comment]
@ItalyPaleAle Would reuse a connection from the caller work for you? Then, you can create a protoClient reusing the same connection that you use to pass it into the SDK client.

The reason I am asking is that return protoClient would make this SDK gRPC specific. In the Java SDK, for example, the connection is abstracted and none of the methods are bound to HTTP or gRPC. This SDK can decide to be different but I think there is value in keeping the abstraction in the long term.

**Comment by ItalyPaleAle** [comment]
@artursouza  are you referring to creating a connection in my code, then instantiating the SDK with `NewClientWithConnection`? I see that.

That could work, although we'd lose out on some automatic plumbing (like reading the env vars to determine the port of the Dapr sidecar). But it may be a workaround.

Just wondering, what's the reason for having support for both HTTP and gRPC? Currently the Go SDK supports gRPC only, and I thought that was a superior way to communicate with the Dapr sidecar, when available?

**Comment by artursouza** [comment]
> @artursouza are you referring to creating a connection in my code, then instantiating the SDK with `NewClientWithConnection`? I see that.
> 
> That could work, although we'd lose out on some automatic plumbing (like reading the env vars to determine the port of the Dapr sidecar). But it may be a workaround.
Correct.

> 
> Just wondering, what's the reason for having support for both HTTP and gRPC? Currently the Go SDK supports gRPC only, and I thought that was a superior way to communicate with the Dapr sidecar, when available?

For now, yes, gRPC is the best way to communicate. Keeping the SDK protocol independent can enable this to change in the long term. Again, the Java SDK chose to keep the communication protocol fully transparent and users can even switch between gRPC and HTTP via system properties. The Python SDK went a different path and is gRPC specific. In the short term there is no gain in keeping the abstraction but it is a one way door, once we cross that there is no way back.

**Comment by ItalyPaleAle** [comment]
Thanks for the context. I understand your concerns and it makes sense.

Then maybe... Could there be a way to expose a method that returns a `*grpc.ClientConn` object with the default options that Dapr uses and that can be passed to `NewClientWithConnection`? This way one could still use `NewClientWithConnection` but wouldn't have to instantiate the client entirely from scratch.

**Comment by artursouza** [comment]
/cc @yaron2 as the SDK maintainer.
/cc @berndverst FYI.

I think the logic to create a gRPC proto client  to Dapr can be separate from creating the abstracted Dapr Client. So, the app can use the gRPC specific client  builder method and reuse that when creating the abstract Dapr Client.

**Comment by ItalyPaleAle** [comment]
Makes sense.

I can propose a PR. I'm on vacation this week but I can do this next week or the one after, depending on how bad work is when I get back 😅

**Comment by daixiang0** [comment]
@ItalyPaleAle I can review it after you propose.

**Comment by yaron2** [comment]
> @yaron2 we would be interested in this feature and I guess it should be easy to implement. Should I open a PR?

Sure, thanks
