### ISSUE TITLE
add support for Configuration API

### ISSUE THREAD

**Issue by dmitsh** [dapr/go-sdk#221]
The Configuration API feature has been implemented in Dapr runtime: https://github.com/dapr/dapr/pull/3606
It needs to be accessible via the SDK.

Also add the docs as part of this issue. See https://github.com/dapr/go-sdk/issues/244

**Comment by skyao** [comment]
I'm back.

Let me take this task.

**Comment by sicoyle** [comment]
can we close this issue as the PR was merged for the configuration api for the go sdk last year?
https://github.com/dapr/go-sdk/pull/200
