### ISSUE TITLE
Add documentation for how to use actors with the go-sdk

### ISSUE THREAD

**Issue by greenie-msft** [dapr/go-sdk#224]
Actors support is now available in the go-sdk. Let's add the necessary documentation on how to use actors with the sdk. 

Content should be located in the daprdocs directory of the repo, which will appear here: https://docs.dapr.io/developing-applications/sdks/go/. It should look similar to how other sdks approached this: https://docs.dapr.io/developing-applications/sdks/python/python-actor/

**Comment by saranvasu** [comment]
Shall I pick this?

**Comment by msfussell** [comment]
@saranvasu - Are you still interested in creating any docs here?

**Comment by rclayton-godaddy** [comment]
@msfussell I'd be interested in writing the docs if I had an example to go by.

**Comment by rclayton-godaddy** [comment]
Ok - I'm a dummy.  I see it in the `examples/` folder.

**Comment by mikeee** [comment]
Addressed by #431
