### ISSUE TITLE
Add docs on how to use Configuration API  

### ISSUE THREAD

**Issue by msfussell** [dapr/go-sdk#244]
Please add documentation that is consistent with the other Go SDK docs on how to use the Configuration API.
The doc / example should live here: https://docs.dapr.io/developing-applications/sdks/go/go-client.

Consider also adding the Go example to How-to for https://v1-6.docs.dapr.io/developing-applications/building-blocks/configuration/howto-manage-configuration/

**Comment by unnsteinngardars** [comment]
Would very much appreciate good documentation on this like the other building blocks have. Also it would be nice to have both Self Hosted(CLI) and Kubernetes instructions.

**Comment by mikeee** [comment]
Looks resolved as of #386
