### ISSUE TITLE
Ensure consistent support for parent trace ID in client requests 

### ISSUE THREAD

**Issue by mchmarny** [dapr/go-sdk#29]
Validate the ability to pass existing context with parent trace ID as an input into the client calls. Ensure the ID is propagated into the client invocation against the Dapr API

**Comment by mchmarny** [comment]
This needs an outline of the test cases, for example: Context resulting from client publishing to Dapr API being used in subsequent client invocations. Also, on the serving side (callback) as well.

**Comment by mchmarny** [comment]
The client already allows passing trace parent ID into each call using the context. #67 adds an explicit method to make this process easier for the user.

**Comment by rainfd** [comment]
why not set WithTraceID as default behavior like withAuthToken?
