### ISSUE TITLE
Consider Once.Do for client initialization

### ISSUE THREAD

**Issue by yaron2** [dapr/go-sdk#32]
If we want to ensure that there's only one gRPC internal client being created we can wrap the internal init logic with Once.Do.

https://golang.org/pkg/sync/#Once.Do

**Comment by mchmarny** [comment]
Doing this implicitly has a downside of preventing users from creating multiple instances of the client which is a valid use-case. I propose we implement this for `client.NewClient()` and use that in all out quick-start docs and leave the other New'ers (list below) as they are: 

* `NewClientWithPort(port string)`
* `NewClientWithAddress(address string)`
* `NewClientWithConnection(conn *grpc.ClientConn)`

**Comment by mchmarny** [comment]
Closing this issue to as creation of the client using defaults creates only one instance of internal resources (issue #33)
