### ISSUE TITLE
Gorilla Mux is no longer maintained

### ISSUE THREAD

**Issue by benc-uk** [dapr/go-sdk#344]
**Is your feature request related to a problem? Please describe.**
I want to use the http service package in the SDK to subscribe to a pub-sub topic, but I don't want to use the `NewService()` function as I need to provide my own HTTP server/router. Previously I used `NewServiceWithMux()` however that only supports Gorilla.

As of end of 2022 Gorilla Mux is no longer maintained, so I have moved to using Chi

The package `github.com/dapr/go-sdk/service/http` is tightly bound to this now no longer supported library

**Describe the solution you'd like**
Support other popular Go HTTP libraries like Chi, Gin or Echo or find a more general purpose solution

**Describe alternatives you've considered**
Not using the Dapr SDK at all for subscripting to topics as it's needlessly complex, and providing very little benefit

**Additional context**
See post about Gorilla here https://github.com/gorilla#gorilla-toolkit

**Comment by spolab** [comment]
+1 on the use of Chi. Looks the nearest neighbour in terms of syntax.

**Comment by andrewweston** [comment]
+1 We use Chi as well. The cleanest approach might be to use the `http.handler` interface as the `mux` arg:

```
func NewServiceWithMux(address string, mux http.Handler) common.Service {
...
```

**Comment by benc-uk** [comment]
For now I've developed by own Chi based helper, which supports subscribing to topics and adding handlers to receive messages on those topics

https://github.com/benc-uk/go-rest-api/blob/main/pkg/dapr/pubsub/helper.go

**Comment by sicoyle** [comment]
Can this be closed please?
