### ISSUE TITLE
Do we need a contribution from the example code about pub/sub here?

### ISSUE THREAD

**Issue by abserari** [dapr/go-sdk#38]
I find that there is only an example code in the readme.md. wondering that if there is a contribution chance for me to add a pub/sub example to go-sdk.

**Comment by mchmarny** [comment]
Absolutely. There are simple examples in [/example/client/main.go](https://github.com/dapr/go-sdk/blob/master/example/client/main.go) but we could always use more. Thank you!

**Comment by abserari** [comment]
I'm sorry for the previous mistakes, I revised them and tested them.
 solved main redeclared by moving Pub. go and Sub. go to in separate folders
![image](https://user-images.githubusercontent.com/32089134/91373570-4a001f00-e849-11ea-9a81-ac828948e5d7.png)
![image](https://user-images.githubusercontent.com/32089134/91373577-53898700-e849-11ea-9052-50625c06c27c.png)

**Comment by abserari** [comment]
I use the pubsub example with natsstreaming component to test the runtime now,https://github.com/dapr/dapr/issues/1996
 use the nats-streaming branch. 👍 https://github.com/abserari/go-sdk/tree/test-the-natsstreaming
