### ISSUE TITLE
Configuration API Subscribe Method Update

### ISSUE THREAD

**Issue by shivamkm07** [dapr/go-sdk#388]
**Describe the bug**

Configuration API subscribe method(https://github.com/dapr/go-sdk/blob/78a1fe63ea19ae2f50b0a276f46571942e0563b2/client/configuration.go#L65) currently is a blocking call(thread calling subscribe method stops at the call) and doesn't return any response to the user till subscribe call is finished. Also to unsubscribe, user would need to do a hack to get the subscriptionID (e.g. https://github.com/dapr/quickstarts/blob/205a59a457febe949035fd27fc098faa526d5ee1/configuration/go/sdk/order-processor/app.go#L41).

This doesn't conform with the sdk-spec (https://github.com/dapr/sig-sdk-spec/blob/main/spec/alpha/configuration.md#subscribeconfigurationresponse). There are few corrections proposed in sdk-spec which details the expected subscribe Configuration response more correctly(https://github.com/dapr/sig-sdk-spec/pull/25). Most of other sdks conform to this as well. 

**To Reproduce**

**Expected behavior**
Subscribe call should return subscription ID after it's invocation, that user can use to unsubscribe later on.

**Comment by shivamkm07** [comment]
Closed by #389

**Comment by mukundansundar** [comment]
@dapr/maintainers-go-sdk add to milestone 1.8

**Comment by mukundansundar** [comment]
Also breaking change
