### ISSUE TITLE
Running the actors example

### ISSUE THREAD

**Issue by arturotrenard** [dapr/go-sdk#390]
**Describe the bug**

On the client everything looks fine. But on the server side I have these messages

![image](https://user-images.githubusercontent.com/65082809/232625315-bf05b116-6be0-4c47-ba10-2e5483c94091.png)

**Comment by mukundansundar** [comment]
@arturotrenard What is the version of `dapr` that you are using?

**Comment by arturotrenard** [comment]
@mukundansundar Dapr version V1.10.5

**Comment by sicoyle** [comment]
I can confirm this is still a present issue on the actors example using:
```
INFO[0000] starting Dapr Runtime -- version edge -- commit fac43dde5571ca52c7c122b8b691596f3a12662c 
```

**Comment by mikeee** [comment]
https://github.com/dapr/go-sdk/actions/runs/7584941308/job/20659728213#step:12:31
The current actor example is passing (as of https://github.com/dapr/dapr/pull/6270 merge)

@arturotrenard are you still having issues we can take a look at?

**Comment by arturotrenard** [comment]
Hi thanks, I haven't checked it for a while, I'll check it and then I'll let you know.

**Comment by rahulpol10** [comment]
Any update on this issue?

I am also facing it 

== APP - xx-account == r... /account.v1.AccountService/CreateAccount
== APP - xx-account == {"time":"2025-03-27T09:17:45.002923+04:00","level":"INFO","msg":"create account handler called."}
== APP - xx-account == [Actor] ERROR: the latest return type string of method "GenerateAccount" is not error
