### ISSUE TITLE
Upgrade go version from 1.19 to 1.20

### ISSUE THREAD

**Issue by hunter007** [dapr/go-sdk#407]
**Describe the solution you'd like**
According the release notes of go1.20, no change for codes.

https://tip.golang.org/doc/go1.20

**Comment by ItalyPaleAle** [comment]
I think we should wait, because this makes it so all consumers of the SDK will need to use 1.20.

We should update the Go version in go.mod only when we need to depend on some new features IMHO. And try to support at least N-1.

**Comment by hunter007** [comment]
Agree with you.

**Comment by mikeee** [comment]
Should the validate-examples github workflow go-version be bumped down to 1.19 in this case if we're still using 1.19?

**Comment by mikeee** [comment]
Addressed by #480
