### ISSUE TITLE
README.md file should include installation snippet

### ISSUE THREAD

**Issue by doe-base** [dapr/go-sdk#432]
Readme file should contain command to install the Dapr Go SDK for easy usage.

**Comment by mikeee** [comment]
What would you like to include? The go-sdk already references how to download and reference the go-sdk.
https://github.com/dapr/go-sdk/blob/main/Readme.md#usage
The above also provides a client example. You can also find client/service examples in the documentation:
https://docs.dapr.io/developing-applications/sdks/go/

**Comment by doe-base** [comment]
previously the [README.md](https://github.com/dapr/go-sdk/blob/main/Readme.md#usage) file did not contain a snippet that shows users how to install the dapr go sdk, but the pull request was made and has been approved.
