### ISSUE TITLE
build: add PR template

### ISSUE THREAD

**Issue by sicoyle** [dapr/go-sdk#449]
The Dapr Go SDK repo should have a PR template for when end users create PRs contributing to the project.

**Describe the solution you'd like**
We should abide by a standardized PR template across all SDK repositories.

To implement, we should add a `pull_request_template.md` file. Something similar to what we have in `dapr/dapr` (https://github.com/dapr/dapr/blob/master/.github/pull_request_template.md), but also considering if we need special additions for SDK specific repositories.

**Additional context**
This will help to improve contributors to easily communicate their changes, as well as maintainers to easily understand what the PR is doing.

**Comment by sicoyle** [comment]
Java SDK PR template to use as inspiration as well: https://github.com/dapr/java-sdk/blob/master/.github/pull_request_template.md

**Comment by sadath-12** [comment]
Can be closed

**Comment by mikeee** [comment]
Closed with #484
