### ISSUE TITLE
build: improve github workflow to check if go mod needs updating

### ISSUE THREAD

**Issue by sicoyle** [dapr/go-sdk#450]
**Is your feature request related to a problem? Please describe.**
Our github workflow should check for if the go mod needs updating when we create pull requests.

**Describe the solution you'd like**
We should have a `go mod tidy` step in the github workflow. This can be something similar to:
https://github.com/dapr/dapr/blob/120247a632262d82e5a02726a7fdb70d46df8fe1/.github/workflows/dapr.yml#L91

**Additional context**
Creating this as a follow up to this PR: https://github.com/dapr/go-sdk/pull/448 and originating issue: https://github.com/dapr/go-sdk/issues/447

**Comment by yaron2** [comment]
Closed via #458
