### ISSUE TITLE
[Release Enhancement] GHA Workflows to Update Versions Automatically

### ISSUE THREAD

**Issue by cicoyle** [dapr/go-sdk#456]
It would be nice to have an automated process that listens for a new tag to be pushed to the `dapr/dapr` repo that updates the version accordingly so we are always up to date on changes and can automate our release candidate testing. This should be automated to minimize the manual steps in the release process.

I propose adding to the existing `dependabot` a GitHub Action Workflow to `dapr/go-sdk` that listens for a new tag on the `dapr/dapr` repo and auto creates a Pull Request that updates that accordingly. [Example updates](https://github.com/dapr/go-sdk/commit/69c6adcdb0dcc18153a9f4d73773ea8d464f772d). Protos will need to be updated/automated with this

Note: Use the `DAPR_BOT` secret

**Comment by mikeee** [comment]
@cicoyle I use _Renovate_ for dependency management, with an enhanced validation suite on the SDK would we be willing to enable renovate on the repo/org?

**Comment by mikeee** [comment]
Renovate has been unpaused and is actively opening PRs for this.
