### ISSUE TITLE
 Implementation of DaprClient methods into the mock client 

### ISSUE THREAD

**Issue by sadath-12** [dapr/go-sdk#485]
**Describe the solution you'd like**

Currently to extend the tests for certain features like stateManager we need to have the complete implementation of mock client method under https://github.com/dapr/go-sdk/blob/main/actor/mock/mock_server.go would be great if we can focus on implementing this first and let any newcomers easily write tests using the mock client

**Describe alternatives you've considered**

**Additional context**

**Comment by mikeee** [comment]
Closing as a close relative of #446
