### ISSUE TITLE
Bulkpublisher should return an error

### ISSUE THREAD

**Issue by mikeee** [dapr/go-sdk#513]
https://github.com/dapr/go-sdk/blob/7e5ee73aa842660f3bb2c958947d1faa3f665022/client/pubsub.go#L136

**Comment by pmannam** [comment]
Hi @mikeee, Bulkpublisher already returns an error right?
https://github.com/dapr/go-sdk/blob/5ef7aa2234d4d4c07769ad31cde223ef11c4e33e/client/pubsub.go#L172-L179
Can you please elaborate the issue

**Comment by mikeee** [comment]
Having a think about it, this seems the most appropriate way. I didn't like the look of returning a `retryid` when the eventmap didn't contain it... but I do think the method is handled gracefully.
