### ISSUE TITLE
go-sdk 1.10.0 still depends on dapr 1.13.0-rc.7

### ISSUE THREAD

**Issue by paulyuk** [dapr/go-sdk#526]
When you `go mod tidy` with reference to v1.10.0 go-sdk, you see state dapr runtime dependency.

```
require (
    github.com/dapr/go-sdk v1.10.0
    github.com/gorilla/mux v1.8.1
)

require (
    github.com/dapr/dapr v1.13.0-rc.7 // indirect 

```

I think that's simply because this go.mod for the sdk needed to be bumped:
https://github.com/dapr/go-sdk/blob/release-1.10/go.mod#L6

**Comment by mikeee** [comment]
Closed by #528
