### ISSUE TITLE
Remove obsolete workflow methods

### ISSUE THREAD

**Issue by famarting** [dapr/go-sdk#634]
equivalent to https://github.com/dapr/dotnet-sdk/issues/1344

the workflow methods defined here https://github.com/dapr/go-sdk/blob/main/client/workflow.go use a deprecated API and we aim to delete them

instead this client should be used https://github.com/dapr/go-sdk/blob/main/workflow/client.go and any docs should be updated to make use of it

**Comment by famarting** [comment]
this issue can be closed since this has been merged https://github.com/dapr/go-sdk/pull/640

this issue does not consist of literally removing the workflow methods, but instead deprecating them and stop advising users to use them

**Comment by mikeee** [comment]
IMO - idiomatic deprecation comments should be added to the relevant client methods before we bottom this issue out completely. e.g.

`client/workflow.go`
```go
...
// StartWorkflowBeta1 starts a workflow using the beta1 spec.
// 
// Deprecated: Please use the workflow client (github.com/dapr/go-sdk/workflow).
// These methods of managing workflows are no longer supported and will be removed in the
// next release.
...
```

Wdyt @famarting?

**Comment by famarting** [comment]
agree agree, will send a PR now adding these comments everywhere

**Comment by mikeee** [comment]
Looks great, thanks for sorting this out 🚀
