### ISSUE TITLE
Strongly Typed SDKs

### ISSUE THREAD

**Issue by bign8** [dapr/go-sdk#7]
## Describe the proposal
Hey folks!  Saw this stuff was released recently and am super excited about it!

One thing I noticed while looking through these SDKs is that they seem to just be exposing the generated gRPC code of the desired language.  I was wondering if it's worth wrapping the gRPC logic in some thin, language specific wrappers.  This could allow language specific patterns to be exposed in each of the SDKs rather than expecting all consumers to understand gRPC right out of the gate.

I threw a branch together of something that it _could_ look like, but wanted to get some feedback on the idea from the maintainers before I go down a rabbit hole.

https://github.com/dapr/go-sdk/compare/master...bign8:language-specific-api

Looking forward to collaborating!

(Also, sorry if this comes across and edgy or short, I have yet to have my morning coffee ☕️)

**Comment by amanbha** [comment]
@bign8 that's great.
Generated sdks are just the beginning, we plan to have strongly typed sdks. Looking forward to collaboration.

**Comment by amanbha** [comment]
@bign8 Perfect, we can start with your PR.
cc @yaron2 as well.

**Comment by mchmarny** [comment]
PTAL at the "bespoke client proposal" PR #18

**Comment by mchmarny** [comment]
Closing this since #18 landed in master
