### ISSUE TITLE
State API should support meta on delete method

### ISSUE THREAD

**Issue by skyao** [dapr/go-sdk#81]
**Is your feature request related to a problem? Please describe.**

I can't delete a state when request level metadata is required.

**Describe the solution you'd like**

In current api definition of client interface, there are to method about delete:

```go
type Client interface {
	// DeleteState deletes content from store using default state options.
	DeleteState(ctx context.Context, store, key string) error

	// DeleteStateWithETag deletes content from store using provided state options and etag.
	DeleteStateWithETag(ctx context.Context, store, key, etag string, opts *StateOptions) error
}
```

suggest to add metadata parameter in state delete api:

```go
type Client interface {
	// keep this simple one no change
	DeleteState(ctx context.Context, store, key string) error

	// change this one, add meta
	// DeleteStateWithETag(ctx context.Context, store, key, etag string, opts *StateOptions) error
       DeleteStateWithETag(ctx context.Context, store, key, etag string, meta map[string]string, opts *StateOptions) error
}
```

Similar to what we do in issue [Adding support for metadata in State API Requests #1965](https://github.com/dapr/dapr/pull/1965)

**Describe alternatives you've considered**

**Additional context**

**Comment by skyao** [comment]
@mchmarny  Hi, Mark, I have submit a PR #82  for this. Please help to review.

**Comment by mchmarny** [comment]
Thanks @skyao, looks good but can you please add/expand existing tests to cover the new parameters.

**Comment by mchmarny** [comment]
done per #82
