### ISSUE TITLE
no redis.yaml

### ISSUE THREAD

**Issue by yhyddr** [dapr/go-sdk#9]
`dapr init `and success.
Then go get github.com/dapr/go-sdk.

and I find it in go/pkg/mod/github.com/dapr/go-sdk and run client.

`client abser$ dapr run --app-id client --protocol grpc --app-port 4000 go run main.go`

then I got an error for I don't have Redis yaml

```
❌  open /Users/abser/go/pkg/mod/github.com/dapr/go-sdk@v0.0.0-20191016010623-4a07ef595834/example/client/components/redis.yaml: no such file or directory
```

**Comment by LMWF** [comment]
This is due to https://github.com/dapr/cli/issues/198.

A workaround is to reinstall dapr as described here - https://github.com/dapr/docs/blob/master/getting-started/environment-setup.md#installing-dapr-cli

**Comment by LMWF** [comment]
The issue above has been fixed in master.
